/*{ gameId: 2585563902,
  platformId: 'NA1',
  gameCreation: 1504029097863,
  gameDuration: 3509,
  queueId: 420,
  mapId: 11,
  seasonId: 9,
  gameVersion: '7.17.200.3955',
  gameMode: 'CLASSIC',
  gameType: 'MATCHED_GAME',
  teams:
   [ { teamId: 100,
       win: 'Win',
       firstBlood: true,
       firstTower: false,
       firstInhibitor: false,
       firstBaron: false,
       firstDragon: false,
       firstRiftHerald: false,
       towerKills: 9,
       inhibitorKills: 1,
       baronKills: 0,
       dragonKills: 2,
       vilemawKills: 0,
       riftHeraldKills: 0,
       dominionVictoryScore: 0,
       bans: [Array] },
     { teamId: 200,
       win: 'Fail',
       firstBlood: false,
       firstTower: true,
       firstInhibitor: true,
       firstBaron: true,
       firstDragon: true,
       firstRiftHerald: false,
       towerKills: 9,
       inhibitorKills: 3,
       baronKills: 2,
       dragonKills: 3,
       vilemawKills: 0,
       riftHeraldKills: 0,
       dominionVictoryScore: 0,
       bans: [Array] } ],
  participants:
   [ { participantId: 1,
       teamId: 100,
       championId: 240,
       spell1Id: 4,
       spell2Id: 12,
       masteries: [Array],
       runes: [Array],
       highestAchievedSeasonTier: 'UNRANKED',
       stats: [Object],
       timeline: [Object] },
     { participantId: 2,
       teamId: 100,
       championId: 29,
       spell1Id: 4,
       spell2Id: 7,
       masteries: [Array],
       runes: [Array],
       highestAchievedSeasonTier: 'GOLD',
       stats: [Object],
       timeline: [Object] },
     { participantId: 3,
       teamId: 100,
       championId: 63,
       spell1Id: 4,
       spell2Id: 3,
       masteries: [Array],
       runes: [Array],
       highestAchievedSeasonTier: 'SILVER',
       stats: [Object],
       timeline: [Object] },
     { participantId: 4,
       teamId: 100,
       championId: 64,
       spell1Id: 4,
       spell2Id: 11,
       masteries: [Array],
       runes: [Array],
       highestAchievedSeasonTier: 'GOLD',
       stats: [Object],
       timeline: [Object] },
     { participantId: 5,
       teamId: 100,
       championId: 1,
       spell1Id: 4,
       spell2Id: 14,
       masteries: [Array],
       runes: [Array],
       highestAchievedSeasonTier: 'SILVER',
       stats: [Object],
       timeline: [Object] },
     { participantId: 6,
       teamId: 200,
       championId: 24,
       spell1Id: 4,
       spell2Id: 11,
       masteries: [Array],
       runes: [Array],
       highestAchievedSeasonTier: 'SILVER',
       stats: [Object],
       timeline: [Object] },
     { participantId: 7,
       teamId: 200,
       championId: 238,
       spell1Id: 14,
       spell2Id: 4,
       masteries: [Array],
       runes: [Array],
       highestAchievedSeasonTier: 'UNRANKED',
       stats: [Object],
       timeline: [Object] },
     { participantId: 8,
       teamId: 200,
       championId: 432,
       spell1Id: 4,
       spell2Id: 3,
       masteries: [Array],
       runes: [Array],
       highestAchievedSeasonTier: 'SILVER',
       stats: [Object],
       timeline: [Object] },
     { participantId: 9,
       teamId: 200,
       championId: 51,
       spell1Id: 4,
       spell2Id: 7,
       masteries: [Array],
       runes: [Array],
       highestAchievedSeasonTier: 'PLATINUM',
       stats: [Object],
       timeline: [Object] },
     { participantId: 10,
       teamId: 200,
       championId: 17,
       spell1Id: 12,
       spell2Id: 4,
       masteries: [Array],
       runes: [Array],
       highestAchievedSeasonTier: 'GOLD',
       stats: [Object],
       timeline: [Object] } ],
  participantIdentities:
   [  { participantId: 1,
      player:
       { platformId: 'NA1',
         accountId: 218739531,
         summonerName: 'TastyKakeKing2',
         summonerId: 57005769,
         currentPlatformId: 'NA1',
         currentAccountId: 218739531,
         matchHistoryUri: '/v1/stats/player_history/NA1/218739531',
         profileIcon: 1606 } },
    { participantId: 2,
      player:
       { platformId: 'NA',
         accountId: 32286644,
         summonerName: 'xouchiesssx',
         summonerId: 19592759,
         currentPlatformId: 'NA1',
         currentAccountId: 32286644,
         matchHistoryUri: '/v1/stats/player_history/NA/32286644',
         profileIcon: 666 } },
    { participantId: 3,
      player:
       { platformId: 'NA',
         accountId: 36991143,
         summonerName: 'hautala147',
         summonerId: 23035037,
         currentPlatformId: 'NA1',
         currentAccountId: 36991143,
         matchHistoryUri: '/v1/stats/player_history/NA/36991143',
         profileIcon: 552 } },
    { participantId: 4,
      player:
       { platformId: 'NA1',
         accountId: 201694529,
         summonerName: 'xPínny',
         summonerId: 38804535,
         currentPlatformId: 'NA1',
         currentAccountId: 201694529,
         matchHistoryUri: '/v1/stats/player_history/NA1/201694529',
         profileIcon: 937 } },
    { participantId: 5,
      player:
       { platformId: 'NA1',
         accountId: 48591434,
         summonerName: 'McLovin1500',
         summonerId: 34202044,
         currentPlatformId: 'NA1',
         currentAccountId: 48591434,
         matchHistoryUri: '/v1/stats/player_history/NA1/48591434',
         profileIcon: 774 } },
    { participantId: 6,
      player:
       { platformId: 'NA1',
         accountId: 50650413,
         summonerName: 'CypherNek',
         summonerId: 36041723,
         currentPlatformId: 'NA1',
         currentAccountId: 50650413,
         matchHistoryUri: '/v1/stats/player_history/NA1/50650413',
         profileIcon: 2095 } },
    { participantId: 7,
      player:
       { platformId: 'NA1',
         accountId: 239003617,
         summonerName: 'Ðeath Mãrk',
         summonerId: 87822154,
         currentPlatformId: 'NA1',
         currentAccountId: 239003617,
         matchHistoryUri: '/v1/stats/player_history/NA1/239003617',
         profileIcon: 1588 } },
    { participantId: 8,
      player:
       { platformId: 'NA1',
         accountId: 43053794,
         summonerName: 'Monkeyfightr',
         summonerId: 30942910,
         currentPlatformId: 'NA1',
         currentAccountId: 43053794,
         matchHistoryUri: '/v1/stats/player_history/NA1/43053794',
         profileIcon: 558 } },
    { participantId: 9,
      player:
       { platformId: 'NA',
         accountId: 36542700,
         summonerName: 'JasonXD',
         summonerId: 22668710,
         currentPlatformId: 'NA1',
         currentAccountId: 36542700,
         matchHistoryUri: '/v1/stats/player_history/NA/36542700',
         profileIcon: 750 } },
    { participantId: 10,
      player:
       { platformId: 'NA1',
         accountId: 47191301,
         summonerName: 'xoMajesty',
         summonerId: 32333042,
         currentPlatformId: 'NA1',
         currentAccountId: 47191301,
         matchHistoryUri: '/v1/stats/player_history/NA1/47191301',
         profileIcon: 782 } } ]
       }*/